### ISSUE TITLE
1897 Electron 

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#103]

**Comment by sarahgaiser** [comment]
brief timeline:
- discovery of cathode rays (1876, Goldstein)
- discovery that cathode rays are particles -> electrons (1897, J. J. Thomson, John S. Townsend and H. A. Wilson)

Thomsons work:
- results: cathode rays are new sort of particles, determined e/m (charge to mass ratio), cathode rays and beta radiation are the same
- setup: I need to look up may old  notes for this

**Comment by s6nadavi** [comment]
This Friday we are going to have a look at the discovery of a very important elementary particle: The electron. The research and efforts to find this tiny particle already started in 1876, when E. Goldstein experimented with cathode rays. Twenty years later the physicist J. J. Thomson concluded that these rays must consist of small, negatively charged particles, which (you've guessed it) are the electrons. 
Let's have a look at the experimental setup _( and how Thomson could prove his hypothesis. ?)_
The main device in his setup was a cathode ray tube. These tubes are built from glass and usually evacuated in an experimental environment. To generate a cathode ray, a high voltage is applied, so that negative particles travel from one electrode (the cathode) to the positively charged anode. Beyond the ring-shaped anode, the stream of particles can be made visible through a specific coating on the glass that is sensitive to cathode rays. To further inspect the particles inside the cathode rays, Thomson used two oppositely charged electric plates. He observed that the cathode ray was deflected from the negatively charged electric plate and therefore concluded, that the particles must be charged negatively. The same was done using magnetic plates of opposite poles (?). In that was Thomson could determine the charge to mass ratio (e/m). 
He observed that the cathode rays consist of very light and negatively charged particles, which he then identified as the electron, we know today.

**Comment by sarahgaiser** [comment]
This Friday we are going to have a look at the discovery of a very important elementary particle: the electron! The quest to find this tiny particle already started in 1876 when E. Goldstein experimented with cathode rays which you can see in the picture. Twenty years later, the physicist J. J. Thomson concluded that these rays must consist of small, negatively charged particles which (you've guessed it) are the electrons.
Let's have a look at the experimental setup:
The main device in his setup was a cathode ray tube. These tubes are built from glass and usually all air is removed inside them, creating a vacuum. To generate a cathode ray, a high voltage is applied so that negative particles travel from one electrode (the cathode) to the positively charged anode. Beyond the anode, the stream of particles can be made visible through a specific coating on the glass. To further inspect the particles inside the cathode rays, Thomson used two oppositely charged electric plates. He observed that the cathode ray was deflected from the negatively charged electric plate and therefore concluded that the particles must be charged negatively. Thomson also investigated the influence of a magnetic field on the rays. He saw that the cathode ray was bent by the magnetic field and could calculate the charge to mass ratio (e/m) from this. He observed that the cathode rays consist of very light and negatively charged particles which he then identified as the electrons we know today.

picture: wikipedia
![Cyclotron_motion_smaller_view](https://user-images.githubusercontent.com/69592687/120818499-f7c7f900-c552-11eb-8ac0-4a67e3c422d1.jpg)
