### ISSUE TITLE
1919 Proton 

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#104]

**Comment by sarahgaiser** [comment]
https://cerncourier.com/a/rutherford-transmutation-and-the-proton/

https://www.tandfonline.com/doi/abs/10.1080/14786431003659230

https://www.britannica.com/science/proton-subatomic-particle

**Comment by s6nadavi** [comment]
Today we will learn about the discovery of a composed particle: the Proton. It is essential in the world of particle physics, since it is one of the building blocks of the atomic nucleus. The physics world at this point already knew about the electron as part of the atom. But what about the atomic nucleus ? 
The experiment we will look at is called the Rutherford experiment, named after the New Zeeland physicist Ernest Rutherford. The conduction of his experiment consisted of scattering alpha-particle on atomic nuclei of the element gold. For this, he used a radioactive source, that sent out alpha particles. These particles are very high energetic and. positively charged. He directed the particles toward a very thin slice of gold and observed in which directions the alpha particle are redirected after hitting the gold foil. And the result really surprised him! Most of the particles went right through. A small number of particles was scattered under small angles. But what does this tell us about about protons ? Well, this result shows us, that the atoms in the gold foil are not dense in matter. Their matter is rather concentrated at a small structure in the atomic centre. In addition, the  
deflection of the positively charged alpha particles showed Rutherford, that the nucleus must be charged positively too.

**Comment by sarahgaiser** [comment]
Today we will learn about the discovery of a composed particle: the proton. It is essential in the world of particle physics, since it is one of the building blocks of the atomic nucleus. When the proton was discovered, the physics world already knew that the electron was part of the atom. But what about the atomic nucleus?
The experiment we will look at is called the Rutherford experiment, named after the New Zeeland physicist Ernest Rutherford. In this experiment Rutherford shot alpha-particles on atomic nuclei of the element gold. Alpha-particles are positively charged particles that appear in the radioactive decay of some elements. Rutherford directed the particles towards a very thin slice of gold and observed in which directions the alpha-particles were flying after they hit the gold foil. And the result really surprised him! Most of the particles went right through. A small number of particles was scattered under small angles. But what does this tell us about about protons? Well, this result shows us that the atoms in the gold foil are not dense, meaning that there is empty space in between them. The matter of each atom is concentrated at a small structure in the atomic centre, the nucleus. In addition, the deflection of the positively charged alpha-particles showed Rutherford that the nucleus must be charged positively too. From this he concluded that a yet unknown sort of particles, the protons, must be the building blocks of each atomic nucleus.

**Comment by sarahgaiser** [comment]
![gold-scattering-experiment diagram](https://user-images.githubusercontent.com/69592687/121717732-d088a300-cae1-11eb-9ff0-cc133928e316.png)
https://chemistrygod.com/gold-scattering-experiment
