### ISSUE TITLE
HUMANS & GRAVITY

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#122]
Talking about the vestibular system in our inner ear.

**Comment by aaceituno01** [comment]
How do humans detect gravity?
Our sense of balance and spatial orientation mainly comes from the vestibular system, which is located in the inner ear.
This system comprises two components: semicircular canals (which detect rotations) and otoliths (which detect linear accelerations). In total, we have three canals (one per spatial axis XYZ).
Now here is where gravity joins the game: if we are still we won't detect anything. That's because gravity sets our "frame of reference" and only when we make a relative movement we can feel something. This feeling is caused by the increasing/decreasing pressure the liquid inside the vestibular system puts on the detectors as seen on the image.
So that's it: we don't experience gravity itself but it sets us a "start position" so we can feel relative movements.

IMAGE SOURCE: https://www.cell.com/current-biology/comments/S0960-9822(05)00837-7
![Picture_1](https://user-images.githubusercontent.com/73119425/120074541-9fe64980-c09d-11eb-894a-1a8e1825c705.jpg)
