### ISSUE TITLE
HUMANS & FRAMES OF REFERENCE

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#123]
We can explain why we get dizzy when we spin: relating the frames of reference of the liquid inside our ears and the rest of the body.

**Comment by aaceituno01** [comment]
Do you know why dancers don’t get dizzy while spinning? Because they know how to apply physics!
If you remember from our previous post, our sense of balance mainly comes from the vestibular system.
So, what happens when we spin? Our whole body becomes a rotating frame of reference while the liquid inside our ears, as it is not "attached" to us, tends to stay still in the original frame of reference. After a few moments, friction and viscosity will start to accelerate the fluid which will rotate with us. At that point, if we suddenly stop spinning, the fluid will keep rotating and we'll feel like we are still spinning until it stops rotating.
But, why do dancers not suffer from this? Well, they've developed a technique named "spotting". It consists on focusing your head on one spot so it only rotates during a brief moment, that little movement is countered by friction and so the liquid doesn't rotate with them, thus they don't get dizzy.

SOURCE: https://balletdancefav.blogspot.com/2020/10/ballet-chaine-turn.html
![image](https://user-images.githubusercontent.com/73119425/120928765-61c4d780-c6e6-11eb-9d9f-a06c2097142c.png)
