### ISSUE TITLE
Desk

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#35]
Create model of desk in news room.

<img width="100" alt="NewsRoomDesk" src="https://user-images.githubusercontent.com/69592687/97806633-f18c3a00-1c5c-11eb-8e8f-f89009fd684d.png">

**Comment by sarahgaiser** [comment]
![NewsRoomExport](https://user-images.githubusercontent.com/69592687/103461342-f1bcba80-4d1d-11eb-8b38-5d9b8ab4b664.jpg)

**Comment by Layfully** [comment]
![obraz](https://user-images.githubusercontent.com/15947565/126664743-a0a2d834-35ef-4fb9-ae35-62ce4ee85e9d.png)
This is how it looks like. I would change the emissive colour of the PNN text on it, because it blends with the rest. What do you think @MPogwizd @sarahgaiser @s6nadavi @Ursuss21 @wa12rior  @DominiqueMClark @tristen-shields @PSSteinmann @melbiel?
