### ISSUE TITLE
Introduction to the Standard Model

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#44]

**Comment by sarahgaiser** [comment]
![StandardModel](https://user-images.githubusercontent.com/69592687/109423218-ec5ab400-79de-11eb-967e-d4636575f08e.jpeg)

**Comment by s6nadavi** [comment]
The standard model of particle physics turned out to be extremely successful in describing elementary particles and how they interact with each other. It is built from 6 quarks and 6 leptons, which each occur in three different generations. Besides, four gauge bosons mediate the fundamental forces acting between the particles. The Higgs boson that was discovered in 2013, gives massive particles their mass.
