### ISSUE TITLE
Electromagnetism

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#49]

**Comment by s6nadavi** [comment]
We could refer to this clip, to learn more about the photon and the phenomenon of light. It's not really particle physics related, but it describes electromagnetic interaction and is probably quite relatable to the audience (and it's very interesting :D ):

https://www.youtube.com/watch?v=IXxZRZxafEQ

**Comment by sarahgaiser** [comment]
could you write something about how electromagnetism bind together atoms (like electron and proton in hydrogen)?
![emWW](https://user-images.githubusercontent.com/69592687/114921499-e6078680-9e2a-11eb-80dd-7ee5ac0a5bfa.jpeg)

**Comment by s6nadavi** [comment]
As you might already know, atoms are bound states. In the easiest case of hydrogen, the atom is made up of one proton and one electron. The negatively charged electron orbits around the positively charged proton. They are bound to each other because of the electrostatic attraction between the positive and negative charges. This binding force is referred to as electromagnetism.

Check out this video, if you want to find out more: 

https://www.youtube.com/watch?v=IXxZRZxafEQ
