### ISSUE TITLE
Top & Bottom quarks

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#50]

**Comment by s6nadavi** [comment]
Finally, let's have a look at the third generation of quarks in the Standard model: the top-quark and bottom-quark. They are by far the heaviest quarks and by being in the third fermion generation they confirm the mass hierarchy that is also seen in charged leptons.  Nevertheless, they share the same properties of charge and spin as the previous generations. Apart from that, the top quark is the heaviest out of all elementary particles in the standard model. Because of its large mass and its short lifetime, it requires high energies and efficient particle detectors to produce and detect this particle experimentally. Consequently, it was discovered nearly 20 years after the bottom quark in April 1995 at the Fermi National Accelerator Laboratory (Fermilab).

If you want to learn more about the challenges physicists faced while searching for the top-quark, check-out this article by the American Physical Society (APS): 

https://www.aps.org/publications/apsnews/200204/history.cfm

**Comment by sarahgaiser** [comment]
![top_bottom](https://user-images.githubusercontent.com/69592687/114160363-1fba2800-9927-11eb-88f7-445ae8dd0ccc.jpeg)
