### ISSUE TITLE
Up & Down quarks

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#52]

**Comment by s6nadavi** [comment]
Now that we have introduced you to the leptons of the Standard Model of particle physics, we want to shine the light on the second category of fermions: the quarks. As for the leptons, there are different quark-flavours that appear in three distinct generations. Let's start with the first generation of quarks with the flavour  up- and down. The up- and down-quarks are particularly important since they are building blocks of the matter that makes up the universe. They are the lightest quarks of the Standard Model and have an electric charge of +2/3 and -1/3 times the elementary charge.  The most prominent particles that are constructed from quarks are the proton and neutron that form atomic nuclei.

**Comment by sarahgaiser** [comment]
![neutron_proton](https://user-images.githubusercontent.com/69592687/112633208-5f6a1580-8e39-11eb-9f14-c025cda8c265.jpeg)
