### ISSUE TITLE
Charged Leptons

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#54]

**Comment by s6nadavi** [comment]
We are about to have a closer look at the Standard Model components! 
Let's start with the leptons. We distinguish between charged and uncharged leptons and both kinds occur in three different generations.
The charged leptons are referred to as electron, muon and tauon. Each of these particles belongs to a different generation. There's a mass hierarchy between the generations so that the electron is lighter than the muon, which is lighter than the tau lepton. 
Apart from the mass, the three leptons are exact copies of each other concerning the electric charge (-1) and the spin (1/2). Since leptons have half-integer spin the appear to be fermions.

**Comment by sarahgaiser** [comment]
![IMG_0E7627A13946-1](https://user-images.githubusercontent.com/69592687/110803115-264d7500-827f-11eb-80c4-764390f0e6c2.jpeg)
