### ISSUE TITLE
BNL

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#55]

**Comment by melbiel** [comment]
Originaly the focus of the @BrookhavenLab was on nuclear research, but it expanded greatly, ranging from accelerating physics to environmental and climate research. One of the notable discoveries was the muon neutrino. Its discovery  is one of the reasons why the leptons, like the quarks, were classified in families. Together with the muon, it forms the second family.
Brookhaven National Lab is also famously known to be one of the two places were the J/Ψ particle was discovered. Due to two independent research groups, (the one at Brookhaven was led by Samuel Ting) the particle got two different names. The name Ting assigned was ”J”.
