### ISSUE TITLE
Jefferson Lab

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#56]

**Comment by melbiel** [comment]
The main research facility of the @Jlab_News is the Continuous Electron Beam Accelerator Facility (CEBAF) accelerator. The CEBAF accelerator consists of two linear accelerators which are connected via two arc sections of steering magnets, which effectively makes it a folded linear accelerator. This allows the electron beam to be continuous rather than a pulsed one like at CERN. This setup is used to analyze the structure of the nucleon and the production and decay of light mesons.

**Comment by Ursuss21** [comment]
![wedex7](https://user-images.githubusercontent.com/44650304/114708719-01d83300-9d2c-11eb-95b3-808b624a7000.png)
