### ISSUE TITLE
CBELSA/TAPS

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#86]
This is an experiment that Naomi and I used to work for. I think it might be nice to also include smaller experiments that mean something to us personally.

**Comment by sarahgaiser** [comment]
Today, we would like to talk about a local experiment at one of our universities: The Crystal Barrel experiment at University of Bonn! The CB experiment is located at the ELSA __add long version of name__ accelerator and uses photons to excite protons higher levels of energy. The excited protons then decay and release for example pions.


okay this needs major reworking but I thought I could start it already :D

**Comment by sarahgaiser** [comment]
![CB-Area](https://user-images.githubusercontent.com/69592687/118787982-9ede3c80-b893-11eb-8bb6-75f793ce2a7c.jpg)

**Comment by sarahgaiser** [comment]
[Barrel.pdf](https://github.com/JPsiInVR/organisation/files/6507425/Barrel.pdf)

**Comment by s6nadavi** [comment]
Today, we would like to share with you an experiment that has a special place in our hearts. It is located at the university of several of our team members. We are talking about the Crystal Barrel (CB) experiment at the University of Bonn! The CB experiment is located at the ELSA ('Elektronen-Stretcher-Anlage') facility. After the electrons have been accelerated in ELSA a photon beam is created. The photon beam is then shot on a very cold hydrogen target.
In that way, the photons can excite protons in hydrogen to higher levels of energy. The excited protons then decay and this decay leads to the generation of other particles, for example, pions. 

Maybe you ask yourself where this funny name of the experiment comes from. Well, it matches the experiment perfectly since the main detector is made up of more than thousands of scintillation crystals and is shaped like a barrel. Hence the name 'Crystal Barrel'.


maybe like that :D ?

**Comment by s6nadavi** [comment]
can you maybe add a circle or something around the barrel, than it would match the text somehow ?^^

**Comment by sarahgaiser** [comment]
Yes, I can do that.
Could you change "...At ELSA we direct a photon beam on a hydrogen target." to "... After the electrons have been accelerated in ELSA a photo beam is created. The photon beam is then shot on a very cold hydrogen target."

**Comment by sarahgaiser** [comment]
<img width="653" alt="cb_with_marker" src="https://user-images.githubusercontent.com/69592687/118791957-7ce6b900-b897-11eb-9715-28f60b23dce8.png">

**Comment by sarahgaiser** [comment]
<img width="642" alt="the_barrel" src="https://user-images.githubusercontent.com/69592687/118792094-9d167800-b897-11eb-871b-e856fd332ef0.png">

**Comment by s6nadavi** [comment]
**Final Version** for Robert:


Today, we would like to share with you an experiment that has a special place in our hearts. It is located at the university of several of our team members. We are talking about the Crystal Barrel (CB) experiment at the University of Bonn! The CB experiment is located at the ELSA ('Elektronen-Stretcher-Anlage') facility. After the electrons have been accelerated in ELSA a photon beam is created. The photon beam is then shot on a very cold hydrogen target.
In that way, the photons can excite protons in hydrogen to higher levels of energy. The excited protons then decay and this decay leads to the generation of other particles, for example, pions. 

Maybe you ask yourself where this funny name of the experiment comes from. Well, it matches the experiment perfectly since the main detector is made up of more than thousands of scintillation crystals and is shaped like a barrel. Hence the name 'Crystal Barrel'.
