### ISSUE TITLE
SuperKamiokande

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/organisation#87]
This is a very big neutrino experiment. We should keep it for later to avoid switching detector types and experimental setups too often.

**Comment by s6nadavi** [comment]
We've already told you about the neutrinos as part of the Standard Model. Neutrinos are quite unique, because of the fact that they are uncharged, nearly massless and only interact via the weak interaction. These properties make it almost impossible to detect. But there are some experiments that managed to build huge neutrino detectors. One of these experiments is the Super-Kamiokande. It is located at the research facility Hida in Japan and is also referred to as Cherenkov-detector. 
This name already indicates, how this experiment is able to detect neutrinos. The setup consists of a huge tank filled with ultra-clean water and the inner tank walls are equipped with hundreds of photomultipliers. If now a neutrino coming from the sun enters the tank it interacts with the water and creates Cherenkov-light (emitted by electrons?). 
This light is amplified and recorded (?) by the photomultipliers in the tank. 

_Maybe :_
Sounds kind of complicated right? This clip nicely summarises the challenge of detecting neutrinos and how SuperKamiokande manages it. 

https://www.youtube.com/watch?v=QcX2d-RmxiI

**Comment by sarahgaiser** [comment]
We've already told you about the neutrinos as part of the Standard Model. Neutrinos are quite unique because they are uncharged, nearly massless and only interact via the weak interaction. These properties make it almost impossible to detect them. Nevertheless, there are several experiments which set out for this task and actually managed to detected neutrinos! 
One of these experiments is SuperKamiokande. It is located at the Hida research facility in Japan deep underground below a mountain. The general setup consists of a huge tank filled with ultra-clean water and inner tank walls covered in hundreds of photomultipliers (which is a fancy physicist's word for very special cameras).
So, how does it work? Why do we need such a huge amount of water? And why is the detector buried under a mountain?
Well, to start with that last question: The stones and soil above the detector shield the experiment from most particles that travel through Earth's atmosphere. Since neutrinos interact so rarely, they can travel through that mountain into the detector. Other particles interact with the atoms in the stones surrounding the detector and get stopped before they can enter it. With the detector hidden away underground, we can assume that only neutrinos leave a signal.
Let's move on to the next question: Why do we need the huge water tank? As mentioned, neutrinos interact very, very rarely with other particles. The idea is to provide a big amount of particles (the electrons in the water) that neutrinos could accidentally bump into to increase the chance of seeing an interaction.
Last but not least, let's talk about the detection mechanism. When a neutrino interacts with an electron in the water, it is possible that a very fast electron or muon is created. As this particle travels through the water, it emits a cone of light. This light can then be detected by the photomultipliers on the wall of the tank. The photomultipliers take a picture of the emitted light and from the shape of the light cone physicist's can gather information on the neutrino.

Sounds kind of complicated right? This clip nicely summarises the challenge of detecting neutrinos and how SuperKamiokande manages it:
https://www.youtube.com/watch?v=QcX2d-RmxiI

**Comment by s6nadavi** [comment]
_Maybe this one:_ 


![super_kamiokande](https://user-images.githubusercontent.com/73640699/119669206-2994dd80-be38-11eb-8397-100ea3b51c3f.jpg)

source: https://www.nature.com/articles/d41586-020-01022-3 (26.05.2021), credit: Kamioka Observatory, ICRR, Univ. Tokyo
