### ISSUE TITLE
CLOUD

### ISSUE THREAD

**Issue by s6nadavi** [JPsiInVR/organisation#90]
https://home.cern/science/experiments/cloud

**Comment by melbiel** [comment]
CLOUD (Cosmics Leaving OUtdoor Droplets) is an experiment, located at CERN, to investigate the influence of cosmic rays on aerosols and cloud formation. The goal is to understand atmospheric aerosols since they are the main source of uncertainty in climate models. To achieve laboratory conditions, the experiment takes place in a 26m3 stainless steel cylinder, filled with synthetic air made from liquid nitrogen and liquid oxygen. By exposing the chamber to adjustable particle beams, the cosmic rays, seen in various altitudes or latitdues, can be simulated. 
The question this experiment is trying to answer is, if ionized molecules contribute to the formation of clouds. In a 2016 released paper the authors state, that the experiment does not support the hypothesis that cosmic rays significantly affect climate.
